### ISSUE TITLE
Client 配置文件问题

### ISSUE THREAD

**Issue by SexyBeast233** [SiJiDo/H#16]
![image](https://user-images.githubusercontent.com/34060869/150263801-ccba646b-5a3e-4b65-9dcf-297cefa1d862.png)
[client]-->[config.ini] 第27行 vuln_xray_webhook = h_server_1:5005
现在默认启动docker建立的镜像名好像为h-server-1与h-worker-1，
之前一个版本部署距离现在有段时间，我忘记是不是我改掉的了 
h-server-11与h_server_1不匹配应该会遇到问题，容器内dig查 只有h-server-1才能解析到对应容器

**Comment by SiJiDo** [comment]
对，这个命令格式有点问题这里这么写是方便client和server在同一台设备上的，因为是分布式的，这个地方可以填ip地址，我进行一下修改吧

**Comment by SiJiDo** [comment]
因为是分布式的，这个地方可以填ip地址， 如果client和server一体的，docker启动容器的命格格式为 文件名_容器名_1 ，打包下载的时候可能项目名是H-main，则会出现H-main_server_1 这样的容器命名
