### ISSUE TITLE
网站打开较慢

### ISSUE THREAD

**Issue by J0eke** [SiJiDo/H#3]
网站打开较慢，页面加载慢的厉害，看了一下Google Fonts的问题。
把/H/app/base/static/assets/css/style.css里面的链接换成国内的镜像，访问速度会快很多。

**Comment by SiJiDo** [comment]
感谢建议，用的国外的前端框架，后续有空就替换，另外index页面会打开较慢，因为会去加载查询celery worker的状态，会有一定的请求时间
