### ISSUE TITLE
涉及到漏洞扫描，页面显示卡进度

### ISSUE THREAD

**Issue by SexyBeast233** [SiJiDo/H#5]
docker部署，部署完毕后 启动扫描 nuclei方式（xray+rad没试），在前端页面一直卡进度条
![image](https://user-images.githubusercontent.com/34060869/147730153-6d9758b4-b591-4725-a926-635e827f3680.png)
在容器内查看日志为
![image](https://user-images.githubusercontent.com/34060869/147730356-88830715-4ce3-44c1-8ebd-cc8756d521a8.png)

**Comment by guguyu1** [comment]
我也遇到了这个问题

**Comment by AcoMt** [comment]
解决了吗

**Comment by 851579181** [comment]
我也遇到了
